// <auto-generated />
using GerenciamentoDeFeirasAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GerenciamentoDeFeirasAPI.Migrations
{
    [DbContext(typeof(ApiContext))]
    partial class ApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GerenciamentoDeFeirasAPI.Models.Feira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AreaP")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CodDist")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodSubPref")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Distrito")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Latitute")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Logradouro")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NomeFeira")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Referencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Regiao5")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Regiao8")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Registro")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Setcens")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SubPrefE")
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Feiras");
                });
#pragma warning restore 612, 618
        }
    }
}
